### ISSUE TITLE
Adding share functionality to the app

### ISSUE THREAD

**Issue by suyalamritanshu** [suyalamritanshu/Live-Video-Call#2]

**Comment by detherminal** [comment]
I want to try to make it.

**Comment by suyalamritanshu** [comment]
Yes, try it do you want me to assign you?

**Comment by detherminal** [comment]
Yes. You can assign me. I will try to make it.

**Comment by suyalamritanshu** [comment]
Sure

**Comment by detherminal** [comment]
@suyalamritanshu . I didn't completely understand my job. Which variable should I make a button for sharing? There isn't anything to share.

**Comment by suyalamritanshu** [comment]
You should start an intent where a share dialog is appeared and the user can send the code
