### ISSUE TITLE
Adding a suitable icon to the app

### ISSUE THREAD

**Issue by suyalamritanshu** [suyalamritanshu/Live-Video-Call#3]

**Comment by albertotn** [comment]
Hi! I can do it if you can assign this issue to me

**Comment by suyalamritanshu** [comment]
Sure, issue is yours

**Comment by albertotn** [comment]
Do you like an icon like this one https://www.flaticon.com/premium-icon/live-chat_3406506?term=live%20call&related_id=3406506 ?

**Comment by suyalamritanshu** [comment]
Yup

**Comment by detherminal** [comment]
Looks like @albertotn couldn't make it. I want to make it. Can you assign me. @suyalamritanshu

**Comment by suyalamritanshu** [comment]
@albertotn are you on the same issue? please tell me others are also waiting
